name: build

on:
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ] 

jobs:
  build-windows-msvc:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: build crtview
        run: |
          cl  source\main.c /O2 /Fe:crtview.exe /MT /link /SUBSYSTEM:WINDOWS
      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: crtview.exe
          path: crtview.exe
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: brew install sdl2 glew
      - name: build crtview
        run: |
          clang -o crtview-mac source/main.c /usr/local/lib/libSDL2.a /usr/local/lib/libGLEW.a -framework OpenGL -Wl,-framework,CoreAudio -Wl,-framework,AudioToolbox -Wl,-weak_framework,CoreHaptics -Wl,-weak_framework,GameController -Wl,-framework,ForceFeedback -lobjc -Wl,-framework,CoreVideo -Wl,-framework,Cocoa -Wl,-framework,Carbon -Wl,-framework,IOKit -Wl,-weak_framework,QuartzCore -Wl,-weak_framework,Metal -liconv -lm
          chmod a+x crtview-mac
          tar -cvf crtview-mac.tar crtview-mac
      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: crtview-mac.tar
          path: crtview-mac.tar
  build-linux-gcc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libsdl2-dev
          sudo apt-get install -qq libglew-dev
      - name: build crtview
        run: |
          gcc -o crtview-linux source/main.c -lSDL2 -lGLEW -lGL -lm -lpthread
          chmod a+x crtview-linux
          tar -cvf crtview-linux.tar crtview-linux
      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: crtview-linux.tar
          path: crtview-linux.tar
